name: Deploy FastAPI 

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}      

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: |
          docker build . -t fastapi_iris

      - name: Test Docker Image Locally
        run: |
          docker run -d -p 8000:8000 --name fastapi_container fastapi_iris
          sleep 5  
          curl -f http://localhost:8000 || (echo "L'API n'a pas démarré correctement" && exit 1)

      - name: Clean up
        run: |
          docker stop fastapi_container
          docker rm fastapi_container
